In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv("Advertising.csv")
X = df.drop('sales',axis=1)
y = df['sales']

In [8]:
from sklearn.preprocessing import PolynomialFeatures

In [10]:
polynomial_converter = PolynomialFeatures(degree=3,include_bias=False)

In [12]:
poly_features = polynomial_converter.fit_transform(X)

In [14]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [18]:
from sklearn.preprocessing import StandardScaler

In [20]:
scaler = StandardScaler()

In [22]:
scaler.fit(X_train)

StandardScaler()

In [24]:
X_train = scaler.transform(X_train)

In [26]:
X_test = scaler.transform(X_test)

In [28]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [30]:
X_test[0]

array([-0.91339472,  1.76259419,  0.68168558, -0.96397506,  0.01521221,
       -0.29304821,  2.31532893,  1.56001049,  0.36991011, -0.87527811,
       -0.53295016, -0.54312331,  0.43542739,  0.18669917, -0.2012045 ,
        2.77252075,  2.09516506,  0.89465642,  0.09868885])

In [34]:
from sklearn.linear_model import Ridge

In [38]:
#help(Ridge)

In [40]:
ridge_model = Ridge(alpha=10)

In [44]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [46]:
test_predictions= ridge_model.predict(X_test)

In [48]:
test_predictions

array([13.7469803 , 19.17764   , 11.8623393 , 16.25574551,  8.92891155,
        8.04595366, 20.13320851, 16.94847676, 10.29219174, 19.78365691,
       10.31758361, 13.44077317, 12.24228062, 23.23864236, 19.12656362,
        9.748809  , 12.84361521,  9.14248129,  8.82504966, 21.46989971,
        8.25222201, 18.8110776 , 28.39227333, 25.06911066,  9.11912241,
       11.8071711 , 20.85199462,  9.31962495, 12.25122303,  9.07811198,
        9.25275556, 19.87154568, 10.55955497,  7.86818084, 17.67220132,
        9.31442423, 10.1539168 ,  9.47802944,  8.63337302, 10.76209179,
       11.63848891, 10.38883411, 10.90270005,  8.40019284, 11.35336224,
       10.3514086 ,  8.00082147, 15.27139854, 12.94761469, 22.49762978,
       10.80165407, 13.01337743, 14.82204895, 11.37354043, 11.69628953,
        7.20576885, 25.53512232, 10.41926545, 17.38798022, 15.10158819])

In [50]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [52]:
MAE=mean_absolute_error(y_test,test_predictions)

In [54]:
MAE

0.5774404204714175

In [56]:
MSE=mean_squared_error(y_test,test_predictions)

In [58]:
MSE

0.8003783071528408

In [60]:
RMSE=np.sqrt(MSE)

In [62]:
RMSE

0.8946386461319681

In [64]:
from sklearn.linear_model import RidgeCV

In [66]:
ridge_cv_model=RidgeCV(alphas=(0.1, 1.0, 10.0))

In [68]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV()

In [70]:
ridge_cv_model.alpha_

0.1

In [78]:
from sklearn.metrics import get_scorer_names

In [84]:
scorer_names=get_scorer_names()
scorer_names

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'matthews_corrcoef',
 'max_error',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_mean_absolute_error',
 'neg_mean_absolute_percentage_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_negative_likelihood_ratio',
 'neg_root_mean_squared_error',
 'normalized_mutual_info_score',
 'positive_likelihood_ratio',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'rand_score',
 'recall',
 'recall_macro',
 'recall_micro',
 'recall_samples',
 'recall_weighted',

In [86]:
ridge_cv_model=RidgeCV(alphas=(0.1, 1.0, 10.0),scoring='neg_mean_absolute_error')

In [88]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(scoring='neg_mean_absolute_error')

In [90]:
ridge_cv_model.alpha_

0.1

In [94]:
test_predictions=ridge_cv_model.predict(X_test)

In [96]:
MAE=mean_absolute_error(y_test,test_predictions)

In [98]:
MSE=mean_squared_error(y_test,test_predictions)

In [100]:
RMSE=np.sqrt(MSE)

In [102]:
MAE

0.42737748843675194

In [104]:
MSE

0.382012988154829

In [106]:
RMSE

0.6180719926956963

In [108]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [110]:
ridge_cv_model.best_score_

-0.3749223340292957

# LASSO- Least absolute shrinkage and selection Operator

In [113]:
from sklearn.linear_model import LassoCV

In [171]:
lasso_cv_model = LassoCV(eps=0.1,n_alphas=100,cv=5)# also can use eps value much smaller loke .001 but will have to give its max_iter value more than 1000

In [177]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, eps=0.1)

In [179]:
lasso_cv_model.alpha_

0.4943070909225828

In [181]:
test_predictions= lasso_cv_model.predict(X_test)

In [183]:
MAE=mean_absolute_error(y_test,test_predictions)

In [185]:
MSE=mean_squared_error(y_test,test_predictions)

In [187]:
RMSE=np.sqrt(MSE)

In [189]:
MAE

0.6541723161252856

In [191]:
MSE

1.2787088713079855

In [193]:
RMSE

1.1308001022762535

In [195]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

# NOTE: Therefore after concluding both Ridge and Lasso Regression we can tell that the is perfornming worse than Ridge as it maximum coefficients are 0 

# but if we take much smaller value of eps like 0.001 and choose its maximum iteratons than its performance will increase and it will take less coef to give value same or better value than ridge regression 

In [199]:
lasso_cv_model = LassoCV(eps=0.001,n_alphas=100,cv=5,max_iter=1000000)

In [201]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, max_iter=1000000)

In [203]:
lasso_cv_model.alpha_

0.004943070909225827

In [205]:
test_predictions= lasso_cv_model.predict(X_test)

In [207]:
MAE=mean_absolute_error(y_test,test_predictions)

In [209]:
MSE=mean_squared_error(y_test,test_predictions)

In [211]:
RMSE=np.sqrt(MSE)

In [213]:
MAE

0.4335034618590069

In [215]:
MSE

0.36761675741990574

In [217]:
RMSE

0.6063140748984026

In [221]:
lasso_cv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

# therefore after much iterations Lasso is better for feature selection because it can shrink unimportant coefficients to zero, effectively removing those features. While Ridge regression reduces all coefficients but doesn't eliminate any features